"""empty message

Revision ID: 907700a142b6
Revises: 
Create Date: 2020-10-16 10:33:42.054898

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '907700a142b6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('blog',
    sa.Column('blog_id', sa.Integer(), nullable=False),
    sa.Column('titulo', sa.String(length=100), nullable=False),
    sa.Column('url', sa.String(length=100), nullable=False),
    sa.Column('video', sa.String(length=1000), nullable=True),
    sa.Column('foto', sa.String(length=1000), nullable=True),
    sa.Column('descripcion', sa.String(length=100), nullable=False),
    sa.Column('subtitulo', sa.String(length=100), nullable=False),
    sa.Column('cuerpo', sa.String(length=10000), nullable=False),
    sa.Column('code', sa.String(length=10000), nullable=True),
    sa.Column('createdate', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('blog_id')
    )
    op.create_table('categoria',
    sa.Column('categoria_id', sa.Integer(), nullable=False),
    sa.Column('categoria', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('categoria_id'),
    sa.UniqueConstraint('categoria')
    )
    op.create_table('roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rolename', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('rolename')
    )
    op.create_table('blocat',
    sa.Column('blog_id', sa.Integer(), nullable=True),
    sa.Column('categoria_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['blog_id'], ['blog.blog_id'], ),
    sa.ForeignKeyConstraint(['categoria_id'], ['categoria.categoria_id'], )
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('password', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('lastname', sa.String(length=100), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('avatar', sa.String(length=100), nullable=True),
    sa.Column('phone', sa.String(length=12), nullable=True),
    sa.Column('createdate', sa.DateTime(), nullable=True),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    op.drop_table('blocat')
    op.drop_table('roles')
    op.drop_table('categoria')
    op.drop_table('blog')
    # ### end Alembic commands ###
